package lec12_01_java_oop_encapsulation;

public class Student {
	private String stName;
	private int stId;
	private char stGender;
	private boolean fullTimeSt;
	private float stGrade;
	
	// LINE 12-17, asked in interview to write the code, so we generally mass up which one is return and which one is void
	// The method name is generated by system, other name will also work
	public String getStName() {
		return stName;
	}
	public void setStName(String stName) {
		this.stName = stName;
	}
	public int getStId() {
		return stId;
	}
	public void setStId(int stId) {
		this.stId = stId;
	}
	public char getStGender() {
		return stGender;
	}
	public void setStGender(char stGender) {
		this.stGender = stGender;
	}
	public boolean isFullTimeSt() {
		return fullTimeSt;
	}
	public void setFullTimeSt(boolean fullTimeSt) {
		this.fullTimeSt = fullTimeSt;
	}
	public float getStGrade() {
		return stGrade;
	}
	public void setStGrade(float stGrade) {
		this.stGrade = stGrade;
	}
	
	
	
	

}
